### ISSUE TITLE
Invisible item frames will not spawn

### ISSUE THREAD

**Issue by rumplepusscat** [techchrism/survival-invisiframes#1]
Hi there,

Just updated my server to 1.16.3 (using Paper & Waterfall) and now, invisible item frames don't seem to spawn/work etc. Slimes are still turned on in config.

May be something else blocking it etc. as have done a few other server changes but had no issues whatsoever before upgrading to 1.16.3.

Other info available if you need it.

Many thanks!

Rumple

**Comment by techchrism** [comment]
Hello,
Sorry it took me a while to get around to looking into this.
I tested with the latest Paper 1.16.3 (v245) and everything seems to be working as expected.
Are you still having problems with the plugin after updating to the latest Paper version?

**Comment by rumplepusscat** [comment]
No worries!

I've updated to v245 and still no difference. I also noticed that the recipe doesn't work (I usually use the command so didn't notice before).

No errors in the console. The config actually looked very different to the default one here on Github so I reset it to that but no change. I've tried reinstalling the plugin already and nothing - I thought at first it might have been PlotSquared blocking it but I've now tried it somewhere without PS.

Any ideas?

Many thanks,

Rumple

**Comment by techchrism** [comment]
Does it work for you when it's the only plugin?
If so, please send me a list of your plugins.

**Comment by rumplepusscat** [comment]
I unfortunately can't test with it being the only plugin right at the moment, but I will try to soon. Here is my plugin list however:

AdvancedHelp, AntiCheatReloaded, ArmorStandEditor, BKCommonLib, BungeeTabListPlus, ChatControl, CleanroomGenerator*, ColoredSigns*, CommandBlocker, CoreProtect, DeluxeMenus, DeluxeTags*, DiscordSRV, dynmap*, Elevators, Essentials, (WorldEdit)FastAsyncWorldEdit, HeadDatabase*, HolographicDisplays, HolographicExtension*, ImageOnMap, LightCleaner, LuckPerms, MaSuiteCore, MaSuiteHomes, MaSuiteTeleports, MaSuiteWarps, Multiverse-Core, NoteBlockAPI, PlaceholderAPI, Plot2Dynmap, PlotSquared, ProtocolLib, SurvivalInvisiframes, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldGuard

The issue is the same on my Hub server, which has (mostly) similar plugins as this (my Creative server).

Thank you for your help!

Rumple

**Comment by techchrism** [comment]
ImageOnMap is the only one that sticks out to me as perhaps causing problems but I don't think it's likely.
When you updated, did you turn the hub server to peaceful mode? The slimes will instantly despawn on peaceful mode so the item frames could still be there, just invisible.
The latest version of the plugin has an alternative (and preferred) method of viewing invisible item frames without items in them.

**Comment by rumplepusscat** [comment]
Apologies - this completely slipped off my radar.

ImageOnMap isn't present on the hub server (though I thought it was at first), so sadly this rules out that being the issue.

The worlds I was trying in I believe were admittedly on peaceful, but I still couldn't place anything in any item frame.

Have updated to the latest version, and still no luck. Frustrating and bizarre as this plugin was excellent beforehand and I'm sure it's an issue on my end - just not sure what...! Have completely reinstalled the plugin a few times.

**Comment by techchrism** [comment]
Something you could try which I call the "Thanos method" is to make a copy of the server and remove half the plugins to see which half was causing issues. Keep doing this until the frames work and you'll be able to figure out fairly quickly which plugin/config was the issue.
